name: Free Steam Seeker

on:
  schedule:
    - cron: '0 */1 * * *'
  workflow_dispatch:

env:
  CHAT_ID: ${{secrets.CHAT_ID}}
  BOT_TOKEN: ${{secrets.BOT_TOKEN}}
  SAVED_ID_PATH: ${{secrets.SAVED_ID_PATH}}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Install Requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run App
        run: python main.py
      - name: Commit Files
        run: |
          git config --local user.email misha-ch@bk.ru
          git config --local user.name DarkNOD-del
          git commit -am "Updated Last ID" || true
      - name: Push Changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
        env:
          CI: true
        
