name: Free Steam Seeker

on:
  schedule:
    - cron: '* * * * *'
  workflow_dispatch:

env:
  CHAT_ID: ${{secrets.CHAT_ID}}
  BOT_TOKEN: ${{secrets.BOT_TOKEN}}
  SAVED_ID_PATH: ${{secrets.SAVED_ID_PATH}}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Install Python v3.10.8
        uses: actions/setup-python@v5
        with:
          python-version: '3.10.8' 
      - name: Install Requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run App
        run: python main.py
      - name: Commit Files
        run: |
          git config --local user.email ${{ secrets.GIT_EMAIL }}
          git config --local user.name ${{ secrets.GIT_NAME }}
          git commit -am "Updated Last ID" || true
      - name: Push Changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
        env:
          CI: true
        
