name: Free Steam Seeker

on:
  push:

jobs:
  Flow-Work:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Run App
        run: python main.py
        
